shixun/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from app1 import views
from shixun import settings

urlpatterns = [
    path('admin/', admin.site.urls), # 银行经理
    path('register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.home, name="home"),
    path('farmer_information/', views.farmer_information_view, name='information'),  # 填写个人信息
    # path('farmer/view/', views.view_farmer_information, name='view_farmer_information'), #查看个人信息
    path('farmer/<int:farmer_id>/edit/', views.edit_farmer_information, name='edit_farmer_information'),  # 编辑个人信息
    path('farmer/<int:farmer_id>/family_info/', views.fill_family_info, name='fill_family_info'),  # 填写家庭成员
    path('family/info/view/', views.view_family_info, name='view_family_info'),  # 查看家庭成员
    path('farmer/<int:family_id>/edit_info/', views.edit_family_info, name='edit_family_info'),  # 修改家庭信息
    path('family/<int:farmer_id>/finance/', views.add_family_finance, name='add_family_finance'),  # 填写家庭收支
    path('farmer/<int:farmer_id>/edit/income-expense/', views.edit_income_expense, name='edit_income_expense'),  # 修改家庭收支
    path('add/<int:farmer_id>/asset/liability/', views.add_asset_liability, name='add_asset_liability'),  # 填写资产负债情况
    path('edit/<int:farmer_id>/asset/liability/', views.edit_asset_liability, name='edit_asset_liability'),  # 修改资产负债情况
    path('add/<int:farmer_id>/business/info/', views.add_business_info, name='add_business_info'),  # 填写经营信息
    path('edit/<int:farmer_id>/business/info/', views.edit_business_info, name='edit_business_info'),  # 修改经营信息
    path('add/<int:farmer_id>/loan/', views.loan_application, name='loan_application'),  # 申请贷款
    path('view/loan/', views.view_loan, name="view_loan"),  # 查看审批情况
    path('farmer/list/', views.farmer_list),  # 功能列表
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models

from django.db import models

class Farmer_User(models.Model):
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    last_login = models.DateTimeField(verbose_name='Last Login', blank=True, null=True)


# 个人信息表
class Farmer(models.Model):
    name = models.CharField(max_length=255, verbose_name='户主姓名')
    id_number = models.CharField(max_length=18, verbose_name='身份证号')
    gender = models.CharField(max_length=10, verbose_name='性别')
    phone_number = models.CharField(max_length=20, verbose_name='手机号码')
    is_local_resident = models.BooleanField(verbose_name='本地常住')
    local_residence_years = models.IntegerField(verbose_name='本地居住年限')
    political_status = models.CharField(max_length=255, verbose_name='政治面貌')
    occupation = models.CharField(max_length=255, verbose_name='个人职业')
    health_condition = models.CharField(max_length=255, verbose_name='健康状况')
    personal_qualities = models.CharField(max_length=255, verbose_name='个人品质')
    marital_status = models.CharField(max_length=255, verbose_name='婚姻状况')
    education_level = models.CharField(max_length=255, verbose_name='文化程度')
    region = models.CharField(max_length=255, verbose_name='所属区域')


    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "基本信息表"
        verbose_name_plural = "基本信息"


# 家庭成员信息
class FamilyMember(models.Model):
    farmer = models.ForeignKey(Farmer, on_delete=models.CASCADE,verbose_name="户主姓名")
    name = models.CharField(max_length=255, verbose_name="姓名")  # 姓名
    relationship = models.CharField(max_length=255, verbose_name='与户主关系')  # 与户主关系
    id_number = models.CharField(max_length=18, verbose_name='身份证号')  # 身份证号
    contact = models.CharField(max_length=20, verbose_name='联系方式')  # 联系方式

    class Meta:
        verbose_name = "家庭信息表"
        verbose_name_plural = "家庭信息"


# 资产负债情况
class AssetLiability(models.Model):
    farmer = models.OneToOneField(Farmer, on_delete=models.CASCADE,verbose_name="户主姓名")
    house_count = models.IntegerField(verbose_name='农房套数')
    house_area = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='面积')
    house_value = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='农房价值')
    car_count = models.IntegerField(verbose_name='汽车数量')
    car_value = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='汽车价值')
    machinery_count = models.IntegerField(verbose_name='农用机械数量')
    machinery_value = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='农用机械价值')
    image = models.ImageField(upload_to='media/', null=True, blank=True, verbose_name='图片附件')  # 图片附件字段

    def __str__(self):
        return str(self.farmer)

    class Meta:
        verbose_name = "资产负债情况"
        verbose_name_plural = "资产负债情况"


# 家庭收支信息
class IncomeExpense(models.Model):
    farmer = models.OneToOneField(Farmer, on_delete=models.CASCADE,verbose_name="户主姓名")
    labor_population = models.IntegerField(verbose_name='劳动人口')
    dependent_population = models.IntegerField(verbose_name='供养人口')
    annual_income = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='家庭年收入')
    operating_income = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='经营收入总和')
    other_income = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='其他收入')
    expenditure = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='家庭支出')
    operating_cost = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='经营成本')
    tax_expense = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='税费支出总和')
    living_expense = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='生活支出')

    class Meta:
        verbose_name = "家庭收支信息"
        verbose_name_plural = "家庭收支信息"


# 经营信息
class BusinessInfo(models.Model):
    farmer = models.OneToOneField(Farmer, on_delete=models.CASCADE,verbose_name="户主姓名")
    enterprise_name = models.CharField(max_length=255, verbose_name='企业名称')
    production_cycle = models.CharField(max_length=255, verbose_name='生产经营周期')
    awards = models.CharField(max_length=255, verbose_name='获奖情况')
    agricultural_subsidy = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='农业补贴（元/年）')
    agricultural_insurance = models.BooleanField(verbose_name='是否参保农业保险')
    business_license = models.ImageField(upload_to='business/licenses/', null=True, blank=True, verbose_name='营业执照')

    class Meta:
        verbose_name = "经营信息"
        verbose_name_plural = "经营信息"


# 贷款授信
class LoanCredit(models.Model):
    STATUS_CHOICES = [
        ('pending', '待审核'),
        ('approved', '已通过'),
        ('rejected', '未通过'),
    ]

    farmer = models.OneToOneField(Farmer, on_delete=models.CASCADE,verbose_name="户主姓名")
    name = models.CharField(max_length=255, verbose_name="姓名")  # 姓名
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending', verbose_name='审核状态')
    loan_amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='贷款金额')

    class Meta:
        verbose_name = "最终审核"
        verbose_name_plural = "最终审核"


def __str__(self):
    return self.username

app1/views.py
from django.contrib.auth import login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

from . import models
from .forms import RegistrationForm, LoginForm, FarmerInformationForm, FarmerEditForm, FamilyMemberForm, \
    IncomeExpenseForm, AssetLiabilityForm, BusinessInfoForm, LoanApplicationForm
from .models import Farmer, FamilyMember, IncomeExpense, AssetLiability, BusinessInfo, LoanCredit


# 注册
def user_register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'register.html', {'form': form})


# 登录
def user_login(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {'form': form})
    form = LoginForm(data=request.POST)
    if not form.is_valid():
        return render(request, "login.html", {'form': form})
    user = form.cleaned_data['username']
    pwd = form.cleaned_data['password']
    user_object = models.Farmer_User.objects.filter(username=user, password=pwd).first()
    if not user_object:
        return render(request, "login.html", {'form': form, 'error': "用户名或密码错误"})
    request.session['info'] = {"id": user_object.id, 'name': user_object.username}
    # 设置一个时间为一周
    request.session.set_expiry(60 * 60 * 24 * 7)
    return redirect('home')

#主页面
def home(request):
    if 'info' in request.session:
        # 用户已登录，隐藏登录与注册按钮
        show_login_register = False
    else:
        # 用户未登录，显示登录与注册按钮
        show_login_register = True
    return render(request, "home.html", {'show_login_register': show_login_register})

# 退出
def user_logout(request):
    logout(request)
    return redirect('home')  # 注销成功后重定向到主页面


# 填写个人信息
def farmer_information_view(request):
    if request.method == 'POST':
        form = FarmerInformationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = FarmerInformationForm()
    return render(request, 'farmer_information.html', {'form': form})


# 修改个人信息
def edit_farmer_information(request, farmer_id):
    farmer = get_object_or_404(Farmer, pk=farmer_id)
    if request.method == 'POST':
        form = FarmerEditForm(request.POST, instance=farmer)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = FarmerEditForm(instance=farmer)
    context = {'form': form, 'farmer': farmer}
    return render(request, 'edit_farmer.html', context)

#个人信息界面
def farmer_list(request):
    return render(request, 'farmer_list.html')


# 填写家庭信息
def fill_family_info(request, farmer_id):
    farmer = get_object_or_404(Farmer, pk=farmer_id)
    if request.method == 'POST':
        form = FamilyMemberForm(request.POST)
        if form.is_valid():
            family_member = form.save(commit=False)
            family_member.farmer = farmer
            family_member.save()
            return redirect('home')
    else:
        form = FamilyMemberForm()
    context = {'form': form}
    return render(request, 'fill_family_info.html', context)


# 查询家庭信息
def view_family_info(request):
    families = FamilyMember.objects.all()
    context = {'families': families}
    return render(request, 'view_family_info.html', context)


# 修改家庭信息
def edit_family_info(request, family_id):
    family = get_object_or_404(FamilyMember, pk=family_id)
    if request.method == 'POST':
        form = FamilyMemberForm(request.POST, instance=family)
        if form.is_valid():
            form.save()
            return redirect('view_family_info')
    else:
        form = FamilyMemberForm(instance=family)

    context = {'form': form, 'family': family}
    return render(request, 'edit_family_info.html', context)


# 填写家庭收支
def add_family_finance(request, farmer_id):
    farmer = get_object_or_404(Farmer, pk=farmer_id)

    if request.method == 'POST':
        form = IncomeExpenseForm(request.POST)
        if form.is_valid():
            finance = form.save(commit=False)
            finance.farmer = farmer
            finance.save()
            return redirect('home', farmer_id=farmer_id)
    else:
        form = IncomeExpenseForm()

    context = {'farmer': farmer, 'form': form}
    return render(request, 'add_family_finance.html', context)


# 修改家庭收支
def edit_income_expense(request, farmer_id):
    farmer = get_object_or_404(Farmer, pk=farmer_id)
    income_expense, created = IncomeExpense.objects.get_or_create(farmer=farmer)

    if request.method == 'POST':
        form = IncomeExpenseForm(request.POST, instance=income_expense)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = IncomeExpenseForm(instance=income_expense)

    context = {'form': form, 'farmer': farmer}
    return render(request, 'edit_income_expense.html', context)


# 填写资产负债情况
def add_asset_liability(request, farmer_id):
    farmer = get_object_or_404(Farmer, pk=farmer_id)
    if request.method == 'POST':
        form = AssetLiabilityForm(request.POST, request.FILES)
        if form.is_valid():
            asset_liability = form.save(commit=False)
            asset_liability.farmer = farmer
            asset_liability.save()
            return redirect('home')
    else:
        form = AssetLiabilityForm()

    context = {'form': form}
    return render(request, 'add_asset_liability.html', context)


# 修改资产负债情况
def edit_asset_liability(request, farmer_id):
    farmer = get_object_or_404(Farmer, pk=farmer_id)
    asset_liability = get_object_or_404(AssetLiability, farmer=farmer)

    if request.method == 'POST':
        form = AssetLiabilityForm(request.POST, request.FILES, instance=asset_liability)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = AssetLiabilityForm(instance=asset_liability)

    context = {'form': form, 'farmer': farmer}
    return render(request, 'edit_asset_liability.html', context)

# 填写经营信息
def add_business_info(request, farmer_id):
    farmer = get_object_or_404(Farmer, id=farmer_id)
    if request.method == 'POST':
        form = BusinessInfoForm(request.POST, request.FILES)
        if form.is_valid():
            business_info = form.save(commit=False)
            business_info.farmer = farmer
            business_info.save()
            return redirect('home', farmer_id=farmer_id)
    else:
        form = BusinessInfoForm()
    context = {
        'form': form,
        'farmer_id': farmer_id,
    }
    return render(request, 'add_business_info.html', context)

# 修改经营信息
def edit_business_info(request, farmer_id):
    farmer = get_object_or_404(Farmer, id=farmer_id)
    try:
        business_info = BusinessInfo.objects.get(farmer=farmer)
    except BusinessInfo.DoesNotExist:
        business_info = None
    if request.method == 'POST':
        form = BusinessInfoForm(request.POST, request.FILES, instance=business_info)
        if form.is_valid():
            business_info = form.save(commit=False)
            business_info.farmer = farmer
            business_info.save()
            return redirect('home')
    else:
        form = BusinessInfoForm(instance=business_info)

    context = {
        'form': form,
        'farmer_id': farmer_id,
    }
    return render(request, 'edit_business_info.html', context)

# 贷款授信
def loan_application(request, farmer_id):
    farmer = get_object_or_404(Farmer, id=farmer_id)
    if request.method == 'POST':
        form = LoanApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            loan_info = form.save(commit=False)
            loan_info.farmer = farmer
            loan_info.save()
            return redirect('home')
    else:
        form = LoanApplicationForm()
    context = {
        'form': form,
        'farmer_id': farmer_id,
    }
    return render(request, 'add_loan.html', context)

# 查看审批情况
def view_loan(request):
    loans = LoanCredit.objects.all()
    context = {'loans': loans}
    return render(request, 'view_loan.html', context)

app1/templates/add_asset_liability.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>填写资产负债情况</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">
</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>填写资产负债情况</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/add_business_info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>填写经营信息</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">
</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>填写经营信息</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
            {% if asset_liability.media %}
                <img src="{{ media.url }}" alt="附件图片">
            {% endif %}
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/add_family_finance.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>填写家庭收支信息</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">
</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>填写家庭收支信息</h1>
    <p>户主姓名: {{ farmer.name }}</p>
    <p>身份证号: {{ farmer.id_number }}</p>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">保存</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/add_loan.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>填写贷款申请</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">
</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>填写贷款申请</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/edit_asset_liability.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改资产负债情况</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">

</head>
<body>

<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>修改资产负债情况</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
            {% if asset_liability.media %}
                <img src="{{ media.url }}" alt="附件图片">
            {% endif %}
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/edit_business_info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改经营信息</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">
</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>修改经营信息</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
            {% if business_info.business_license %}
                <p>营业执照: <img src="{{ business_info.business_license.url }}" alt="营业执照"></p>
            {% endif %}
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/edit_farmer.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>农户基本信息修改</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">

</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>

    <h1>编辑农户信息</h1>

    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">户主姓名</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            <label for="id_id_number">身份证号</label>
            {{ form.id_number }}
        </div>
        <div class="form-group">
            <label for="id_gender">性别</label>
            {{ form.gender }}
        </div>
        <div class="form-group">
            <label for="id_phone_number">手机号码</label>
            {{ form.phone_number }}
        </div>
        <div class="form-group">
            <label for="id_is_local_resident">本地是否常住</label>
            <select class="form-control" id="id_is_local_resident" name="is_local_resident">
                <option value="true" {% if form.is_local_resident.value == 'true' %}selected{% endif %}>是</option>
                <option value="false" {% if form.is_local_resident.value == 'false' %}selected{% endif %}>否</option>
            </select>
        </div>
        <div class="form-group">
            <label for="id_local_residence_years">本地居住年限</label>
            {{ form.local_residence_years }}
        </div>
        <div class="form-group">
            <label for="id_political_status">政治面貌</label>
            {{ form.political_status }}
        </div>
        <div class="form-group">
            <label for="id_occupation">个人职业</label>
            {{ form.occupation }}
        </div>
        <div class="form-group">
            <label for="id_health_condition">健康状况</label>
            {{ form.health_condition }}
        </div>
        <div class="form-group">
            <label for="id_personal_qualities">个人品质</label>
            {{ form.personal_qualities }}
        </div>
        <div class="form-group">
            <label for="id_marital_status">婚姻状况</label>
            {{ form.marital_status }}
        </div>
        <div class="form-group">
            <label for="id_education_level">文化程度</label>
            {{ form.education_level }}
        </div>
        <div class="form-group">
            <label for="id_region">所属区域</label>
            {{ form.region }}
        </div>
        <div class="form-group">
            <label for="id_status">状态</label>
            {{ form.status }}
        </div>
        <div class="form-group">
            <button type="submit">保存</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/edit_income_expense.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改家庭收支信息</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">

</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>修改家庭收支信息</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <button class="btn btn-primary" type="submit">提交</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>

app1/templates/farmer_information.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>填写农户基本信息</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'css/back.css' %}">

</head>
<body>
<div class="container">
    <button class="back" onclick="goBack()">返回</button>
    <h1>填写农户基本信息</h1>
    <form method="POST" action="{% url 'information' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">户主姓名:</label>
            <input type="text" id="id_name" name="name" required>
        </div>

        <div class="form-group">
            <label for="id_id_number">身份证号:</label>
            <input type="text" id="id_id_number" name="id_number" required>
        </div>

        <div class="form-group">
            <label for="id_gender">性别:</label>
            <select id="id_gender" name="gender" required>
                <option value="male">男</option>
                <option value="female">女</option>
            </select>
        </div>

        <div class="form-group">
            <label for="id_phone_number">手机号码:</label>
            <input type="text" id="id_phone_number" name="phone_number" required>
        </div>

        <div class="form-group">
            <label for="id_is_local_resident">本地是否常住</label>
            <select class="form-control" id="id_is_local_resident" name="is_local_resident">
                <option value="true">是</option>
                <option value="false">否</option>
            </select>
        </div>

        <div class="form-group">
            <label for="id_local_residence_years">本地居住年限:</label>
            <input type="number" id="id_local_residence_years" name="local_residence_years" required>
        </div>

        <div class="form-group">
            <label for="id_political_status">政治面貌:</label>
            <select id="id_political_status" name="political_status" required>
                <option value="">选择政治面貌</option>
                <option value="群众">群众</option>
                <option value="党员">党员</option>
                <option value="团员">团员</option>
            </select>
        </div>

        <div class="form-group">
            <label for="id_occupation">个人职业:</label>
            <input type="text" id="id_occupation" name="occupation" required>
        </div>

        <div class="form-group">
            <label for="id_health_condition">健康状况:</label>
            <select id="id_health_condition" name="health_condition" required>
                <option value="">选择健康状况</option>
                <option value="健康">健康</option>
                <option value="亚健康">亚健康</option>
                <option value="不健康">不健康</option>
            </select>
        </div>

        <div class="form-group">
            <label for="id_personal_qualities">个人品质:</label>
            <input type="text" id="id_personal_qualities" name="personal_qualities" required>
        </div>

        <div class="form-group">
            <label for="id_marital_status">婚姻状况:</label>
            <select id="id_marital_status" name="marital_status" required>
                <option value="">选择婚姻状况</option>
                <option value="已婚">已婚</option>
                <option value="未婚">未婚</option>
                <option value="离异">离异</option>
            </select>
        </div>

        <div class="form-group">
            <label for="id_education_level">文化程度:</label>
            <select id="id_education_level" name="education_level" required>
                <option value="">选择文化程度</option>
                <option value="小学">小学</option>
                <option value="初中">初中</option>
                <option value="高中">高中</option>
                <option value="大专">大专</option>
                <option value="本科">本科</option>
                <option value="硕士">硕士</option>
                <option value="博士">博士</option>
            </select>
        </div>

        <div class="form-group">
            <label for="id_region">所属区域:</label>
            <input type="text" id="id_region" name="region" required>
        </div>

        <div class="form-group">
            <button type="submit">提交</button>
        </div>
    </form>
</div>
<script>
    function goBack() {
        history.back();
    }
</script>
</body>
</html>